METRIC = {
    "avg": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-avg-aggregation.html",
        "doc": """
            A single-value metrics aggregation that computes the average of numeric values that are extracted from the aggregated documents. These values can be extracted either from specific numeric fields in the documents, or be generated by a provided script.
        """,
        "parameters": {
            "field": {"type": str, "required": True},
            "missing": {"type": "any"},
            "script": {"type": dict},
        },
        "returns": ["value"],
    },
    "boxplot": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-boxplot-aggregation.html",
        "parameters": {
            "field": {"type": str, "required": True},
            "compression": {"type": int, "default": 100},
            "missing": {"type": "any"},
        },
        "returns": ["min", "max", "q1", "q2", "q3"],
    },
    "cardinality": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html",
        "parameters": {
            "field": {"type": str, "required": True},
            "precision_threshold": {"type": int, "default": 3000},
            "missing": {"type": "any"},
            "script": {"type": dict},
        },
        "returns": ["value"],
    },
    "extended_stats": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-extendedstats-aggregation.html",
        "parameters": {
            "field": {"type": str, "required": True},
            "sigma": {"type": float, "default": 3.},
            "missing": {"type": "any"},
            "script": {"type": dict},
        },
        "returns": [
            "count", "min", "max", "avg", "sum", "sum_of_squares",
            "variance", "variance_population", "variance_sampling",
            "std_deviation", "std_deviation_population", "std_deviation_sampling", "std_deviation_bounds"
        ],
    },
    "geo_bounds": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-geobounds-aggregation.html",
        "parameters": {
            "field": {"type": str, "required": True},
            "wrap_longitude": {"type": bool, "default": True},
        },
        "returns": ["top_left", "bottom_right"],
    },
    "geo_centroid": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-geocentroid-aggregation.html",
        "parameters": {
            "field": {"type": str, "required": True},
        },
        "returns": ["location"],
    },
    "matrix_stats": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-matrix-stats-aggregation.html",
        "parameters": {
            "fields": {"type": list, "required": True},
            "mode": {"type": str, "default": "avg"},
            "missing": {"type": "any"},
        },
        "returns": ["fields"],
    },
    "max": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-max-aggregation.html",
        "parameters": {
            "field": {"type": str, "required": True},
            "missing": {"type": "any"},
            "script": {"type": dict},
        },
        "returns": ["value"],
    },
    "median_absolute_deviation": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-median-absolute-deviation-aggregation.html",
        "parameters": {
            "field": {"type": str, "required": True},
            "compression": {"type": int, "default": 1000},
            "missing": {"type": "any"},
            "script": {"type": dict},
        },
        "returns": ["value"],
    },
    "min": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-min-aggregation.html",
        "parameters": {
            "field": {"type": str, "required": True},
            "missing": {"type": "any"},
            "script": {"type": dict},
        },
        "returns": ["value"],
    },
    "percentile_ranks": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-rank-aggregation.html",
        "parameters": {
            "field": {"type": str, "required": True},
            "values": {"type": list, "required": True},
            "keyed": {"type": bool, "default": True},
            "hdr.number_of_significant_value_digits": {"type": int},
            "missing": {"type": "any"},
            "script": {"type": dict},
        },
        "returns": ["values"],
    },
    "percentiles": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html",
        "parameters": {
            "field": {"type": str, "required": True},
            "percents": {"type": list, "default": (1, 5, 25, 50, 75, 95, 99)},
            "keyed": {"type": bool, "default": True},
            "tdigest.compression": {"type": int, "default": 100},
            "hdr.number_of_significant_value_digits": {"type": int},
            "missing": {"type": "any"},
            "script": {"type": dict},
        },
        "returns": ["values"],
    },
    "rate": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-rate-aggregation.html",
        "parameters": {
            "unit": {"type": str, "required": True},
            "field": {"type": str},
            "script": {"type": dict},
        },
        "returns": ["value"],
    },
    "scripted_metric": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-scripted-metric-aggregation.html",
        "parameters": {
            "map_script": {"type": str, "required": True},
            "combine_script": {"type": str, "required": True},
            "reduce_script": {"type": str, "required": True},
            "init_script": {"type": str},
            "params": {"type": dict},
        },
        "returns": ["value"],
    },
    "stats": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-stats-aggregation.html",
        "parameters": {
            "field": {"type": str, "required": True},
            "missing": {"type": "any"},
        },
        "returns": ["count", "min", "max", "sum", "count", "avg"],
    },
    "string_stats": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-string-stats-aggregation.html",
        "parameters": {
            "field": {"type": str, "required": True},
            "show_distribution": {"type": bool, "default": False},
            "missing": {"type": "any"},
        },
        "returns": ["count", "min_length", "max_length", "avg_length", "entropy", "distribution"],
    },
    "sum": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-sum-aggregation.html",
        "parameters": {
            "field": {"type": str, "required": True},
            "missing": {"type": "any"},
            "script": {"type": dict},
        },
        "returns": ["value"],
    },
    "t_test": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-ttest-aggregation.html",
        "parameters": {
            "a.field": {"type": str, "required": True},
            "b.field": {"type": str, "required": True},
            "type": {"type": str, "required": True},
            "a.filter": {"type": dict},
            "b.filter": {"type": dict},
            "script": {"type": dict},
        },
        "returns": ["value"],
    },
    "top_hits": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-hits-aggregation.html",
        "parameters": {
            # TODO: quite incomplete
            "size": {"type": int, "required": True},
            "sort": {"type": dict},
            "_source": {"type": dict},
        },
        "returns": ["hits"],
    },
    "top_metrics": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-metrics.html",
        "parameters": {
            "metrics": {"type": dict, "required": True},
            "sort": {"type": dict},
        },
        "returns": ["top"],
    },
    "value_count": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-valuecount-aggregation.html",
        "parameters": {
            "field": {"type": str, "required": True},
            "script": {"type": dict},
        },
        "returns": ["value"],
    },
    "weighted_avg": {
        "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-weight-avg-aggregation.html",
        "parameters": {
            "value.field": {"type": str, "required": True},
            "weight.field": {"type": str, "required": True},
            "value.missing": {"type": "any"},
            "weight.missing": {"type": "any"},
            "format": {"type": str},
            "value_type": {"type": str},
            "script": {"type": dict},
        },
        "returns": ["value"],
    },
}
